services:
  - type: web
    name: beach-volley-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: beach-volley-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
